#!/usr/bin/env ruby

require 'rest-client'
require 'yaml'

begin
	config = YAML.load_file("config.yml")
rescue Errno::ENOENT
	puts "Please create config file: \"config.yml\""
	exit 1
end

config_variables = %w[telegram_api_token telegram_chat_id filename]

# Make sure config file isn't empty.
unless config
	puts "Config file is empty. Please define #{config_variables.join(", ")}."
	exit 1
end

# Check that config file is correct.
config_variables.each do |var|
	if config[var].nil?
		puts "Please define \"#{var}\" in the config file."
		exit 1
	end
end
telegram_api_token = config["telegram_api_token"]
telegram_chat_id = config["telegram_chat_id"]
$filename = config["filename"]

# Get piped contents from shell.
content = ARGF.read(ARGV.first).to_s

# Create file in memory.
# r - Read only
# b - Binary mode
file = StringIO.new content, "rb"

# Give StringIO a path method.
# Needed for RestClient to treat StringIO as a file.
def file.path
	$filename
end

url = "https://api.telegram.org/bot#{telegram_api_token}/sendDocument"
RestClient.post url, {:document => file, :chat_id => telegram_chat_id, :multipart => true}
